site_name: AND — Information Hub
nav:
  - Home: index.md
  - Market: content/market/market-size.md
  - Design:
    - Menu: content/design/menu-design.md
    - Tipografia (Dislexia): content/design/typography_dyslexia.md
  - Barreiras: content/barriers/sensory_cognitive.md
  - Decisão: content/decision/cognitive_load.md
  - Recomendações: content/recommendations/recommendations.md
  - Casos:
    - Brasil: content/cases/espetinho_do_vini.md
    - Canadá: content/cases/sarang_kitchen.md
    - Reino Unido: content/cases/uk_the_gate.md
  - Legal:
    - Brasil: content/legal/brazil.md
    - Europa: content/legal/europe.md
  - Métricas: content/metrics/key_metrics.md
  - Referências: content/references/references.md
theme:
  name: material
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - attr_list
